version: "3.7"
services:
  app:
    build:
      context: .
    container_name: app
    command: sh app_start.sh
    env_file:
      - .env.example
    ports:
      - ${APP_PORT_EXTERNAL}:${APP_PORT}
    depends_on:
      db_postgre:
        condition: service_healthy

  db_postgre:
    image: postgres:14
    container_name: db_postgres
    ports:
      - ${DATABASE_PORT_EXTERNAL}:${DATABASE_PORT}
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: