version: "3.7"
services:
  app:
    build:
      context: .
    container_name: app
    command: ["/async-python-sprint-4/app_start.sh"]
    env_file:
      - .env
    ports:
      - 9999:8080
    depends_on:
      db_postgre:
        condition: service_healthy

  db_postgre:
    image: postgres:14
    container_name: db_postgres
    ports:
      - 5454:5432
    environment:
      - POSTGRES_DB=async-python-sprint-4
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: