"""use_me

Revision ID: 3906071297b9
Revises: 31ce024ebc04
Create Date: 2023-04-27 16:50:43.031699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3906071297b9'
down_revision = '31ce024ebc04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
